### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by clouless** [scandio/e4-framework#1]
Hi @ataraxie 

After deep dive into E3 I now really want to use E4 :D 

But could you please add a LICENSE file with maybe a MIT License to the project?
Currently it is unclear, what the license is :)

thanks a lot for this great tool :) 

cheers,
Bernhard

**Comment by ataraxie** [comment]
Hi @clouless !

Wow, nice surprise! E4 hasn't really been advertised yet and I've for now used it mainly for testing our own apps - sorry that there's still no proper documentation yet. I just did a clean up and added a LICENSE file. You hit a really good point in time though because just yesterday I finally managed to make the provisioning mechanism work well with different datasets etc. I'll give you a few hints that might be enough for you to get started...

I adapted your `manage-cluster...` script quite a lot - hope that's ok. My version lives in `./docker/confluence-data-center/manage-confluence-cluster.sh`. It's still based on your containers though, i.e. I went away from building my own containers and I now just use my own entry points. I start the cluster with:
```
./manage-confluence-cluster.sh --action create --scale 4 --version 6.15.3 --provkey conf6153_large --nodeheap 8192
```
I run this on a AWS `c5n.9xlarge` instance with 36 CPUs. In my experience it's what's needed to deal with the large dataset and 250 concurrent E4 users.

Then, I run a E4 worker docker container on another `c5n.9xlarge` instance. You can look at `./docker/e4worker/startworker-local.sh` and `startworker.sh` in the same dir. While I could start multiple worker machines/containers I found it easier to just work with one large machine to run all the up to 250 concurrent users required by Atlassian.

Basis for these scripts is this in `/etc/hosts`:
```
SERVER_IP awse4
SERVER_IP confluence-cluster-6153-lb
WORKER_IP e4w
```
And also the `awse4` and `e4w` hosts in `.ssh/config`.

My calculation for the server/worker machines is roughly:
* 1 CPU per 10 concurrent users for both worker and server machines
* 100 MB RAM per 1 user on both worker and server machines
* 50% CPU shares and other tuning to the postgres docker container (see `docker run` command params for the postgres container)
* 8GB heap spaces

While one could decide to use different sizes of machines for different configurations (# nodes and conc. users) I decided to just stick to the big ass `c5n.9xlarge` ones for all the configurations. Keeps it more representative and in the end it's annoying if a machine runs into RAM or CPU bottlenecks (I've had that a lot).

The server docker container is provisioned with a dataset identified by the `provkey` parameter given to the `manage...` thing. It refers to a `tar.gz` file I created (containing confluence-home, -shared-home, and a DB dump, all after the data generator ran) and put on a S3 bucket.

The last config ran is exactly the one in `./example-config.json`. On my local machine, I ran `de.scandio.e4.E4Application` with `--config example-config.json --output-dir /tmp/e4/out` as arguments. This runs the vanilla test scenarios with no app installed.

After each run, I invoke `./docker/e4worker/getlogs.sh` to obtain all the raw data from the worker. I then used to open the *.sqlite file and copied all the data by hand into a Google Spreadsheet, which I've recently started to also automate with `./docker/e4worker/sqldata.rb` and `./docker/e4worker/scale.rb`. I'm currently working on [this spreadsheet](https://docs.google.com/spreadsheets/d/1_p6aBLTE7Djv2NghlWbzRkAjBZYMLnUPSgqBHd3x6GI/edit?usp=sharing) for another app of ours. The tables and charts I put into a Confluence page with some more descriptions and other stuff and send it over to Atlassian.

Hope this helps and let me know if you need more info! I hope you don't feel like I destroyed your `manage...` thing :D

**Comment by clouless** [comment]
Ok thanks for the outline :) Since we are a small startup I am very afraid of the AWS Costs, that is why I am running the Confluence dockerized in my BareMetal Kubernetes Cluster. I have just made snapshots of the database, confluence-home and confluence-share-home (I had these scripts already in place from my Jira Performance test).

So basically I am doing the provisioning step semi-automated.
And I just need a performance tool to measure the Confluence Actions and the Actions of my App.
In these phases:

 * 1Confluence Node without App
 * 1Confluence Node with App
 * 2Confluence Nodes without App
 * 2Confluence Nodes with App
 * 4Confluence Nodes without App
 * 4Confluence Nodes with App

Between the phases I reset the Environment back to its original state (using the snapshots).

I cannot run this much load on my cluster so I will need to see what applies best :)
Currently I am trying to write "confluence-actions" for the JPT Framework, since I am already familiar with it. Currently I am unsure what my best choice it. Might be JPT if it leads to quick results. If not, then E4 should be the best choice. E3 is off the table for sure :D 

But nice thing is: The JPT Actions can easily be ported to E4 since it is both Kotlin with Selenium, and almost same principles apply. Even though I find the Memory and AdaptiveMemory mechanism of JPT very nice to "remember" e.g. pageIds and in other Actions you can do `memory.recall().pageid` to get a random pageId.  

So keep me updated, I will have an eye on e4 and maybe you could do a short "Test on your own Infrastructure" section in the docs, maybe :) 

But no hassle, I am already deep down into your code, and you seem to be in the middle of refactoring in the develop branch, so I don't want to distract you - keep up the good work and finish that first :) 

One tiny thing: In the main readme, the link to the presentation does not really work ^^

cheers,
bg

**Comment by ataraxie** [comment]
Yep sounds good. The refactoring is already done and I removed all branches except master. I'm also remembering pageIds. I'm initially loading a random set of page IDs for all simulated users upon startup via REST. If you can manage to get the VanillaTestPackage to run on your own environment (just start with a number of 50 users and one node and it should be fine) you're mostly good to go. No AWS needed. But of course go ahead and try with JPT first :). But didn't JPT work on AWS as a requirement?

Will fix the README.

**Comment by clouless** [comment]
Wow you are too fast ^^

JPT can also be executed "[on premise](https://github.com/atlassian/jira-performance-tests/blob/master/docs/tests/ON_PREMISE.md)" and that worked fine for my Jira App. (Even though it is badly documented, and I had to find the result files on my own in some strange subdirectories)

I will try both JPT and E4 and then see what works for me. But E4 looks very nice, and I like the idea of just one tool to test any app :) 

I will give you more detailed feedback once I have it up and running (if you are interested).

I wish you a nice rest of the weekend :)

**Comment by ataraxie** [comment]
Yeah same to you! You actually just caught me checking my emails really quick and I then decided to clean up the repo :)

[Here's](https://www.dropbox.com/s/xv8hdhzi8uk40mt/e4-log-n1-u50-1563538264.log?dl=1) the E4 log of my last run with 1 node and 50 users for the VanillaTestPackage. I think it gives a good impression of what's going on. But you might know already anyway if you studied our code. I'm really excited about E4 :)

**Comment by clouless** [comment]
Very nice :) 
I am quite curious of the sqlite db result.
Since I will have decided to feed my JSON (which i put together manually) in this Schema and then have a nice ChartJS and JavaScript to show this as HTML table and chart to send this to Atlassian.
This was it e.g. for Jira:

```
{
  "title": "Average Response Times in ms",
  "oneNodeWithOutApp": {
    "$ref": "2019-06-23--10_52_11--30min--50u--withoutApp--1node--unlimitedCPU--OK",
    "Add Comment": 13110,
    "Browse Boards": 3838,
    "Browse Projects": 5234,
    "My App Action XYZ": 1,
    "Create Issue": 9204,
    "Edit Issue": 12468,
    "Full Add Comment": 17142,
    "Full Create Issue": 111357,
    "Full Edit Issue": 42923,
    "Log In": 6931,
    "Project Summary": 4014,
    "Search with JQL": 11234,
    "View Backlog": 5168,
    "View Board": 8705,
    "View Dashboard": 4813,
    "View Issue": 11808
  },
  "oneNodeWithApp": {
    "$ref": "2019-06-23--12_23_07--30min--50u--withApp--1node--unlimitedCPU--OK--noPreReset",
    "Add Comment": 12541,
    "Browse Boards": 3523,
    "Browse Projects": 5148,
    "My App Action XYZ": 1,
    "Create Issue": 10061,
    "Edit Issue": 12515,
    "Full Add Comment": 16427,
    "Full Create Issue": 115468,
    "Full Edit Issue": 43984,
    "Log In": 7770,
    "Project Summary": 4057,
    "Search with JQL": 11322,
    "View Backlog": 5532,
    "View Board": 8397,
    "View Dashboard": 4892,
    "View Issue": 11612
  },
  "twoNodesWithOutApp": {
    "$ref": "2019-06-23--13_44_28--30min--50u--withoutApp--2node--unlimitedCPU--OK",
    "Add Comment": 11784,
    "Browse Boards": 4099,
    "Browse Projects": 5059,
    "My App Action XYZ": 1,
    "Create Issue": 10413,
    "Edit Issue": 11516,
    "Full Add Comment": 15243,
    "Full Create Issue": 81846,
    "Full Edit Issue": 40092,
    "Log In": 8656,
    "Project Summary": 3804,
    "Search with JQL": 10547,
    "View Backlog": 4959,
    "View Board": 7427,
    "View Dashboard": 4436,
    "View Issue": 10832
  },
  "twoNodesWithApp": {
    "$ref": "2019-06-23--16_36_11--30min--50u--withApp--2node--unlimitedCPU--OK",
    "Add Comment": 13372,
    "Browse Boards": 4103,
    "Browse Projects": 5223,
    "My App Action XYZ": 1,
    "Create Issue": 10622,
    "Edit Issue": 12986,
    "Full Add Comment": 17196,
    "Full Create Issue": 126721,
    "Full Edit Issue": 45380,
    "Log In": 8497,
    "Project Summary": 4206,
    "Search with JQL": 11105,
    "View Backlog": 5279,
    "View Board": 8060,
    "View Dashboard": 4691,
    "View Issue": 11585
  },
  "fourNodesWithOutApp": {
    "$ref": "2019-06-27--19_17_14--30min--50u--withoutApp--4nodes--unlimitedCPU--OK",
    "Add Comment": 11320,
    "Browse Boards": 3888,
    "Browse Projects": 4590,
    "My App Action XYZ": 1,
    "Create Issue": 9965,
    "Edit Issue": 11704,
    "Full Add Comment": 15194,
    "Full Create Issue": 95005,
    "Full Edit Issue": 41421,
    "Log In": 8938,
    "Project Summary": 3780,
    "Search with JQL": 11136,
    "View Backlog": 4996,
    "View Board": 7626,
    "View Dashboard": 4349,
    "View Issue": 10746
  },
  "fourNodesWithApp": {
    "$ref": "2019-06-27--22_04_10--30min--withApp--4nodes--unlimitedCPU--OK",
    "Add Comment": 12464,
    "Browse Boards": 4313,
    "Browse Projects": 5206,
    "My App Action XYZ": 1,
    "Create Issue": 9564,
    "Edit Issue": 13016,
    "Full Add Comment": 16455,
    "Full Create Issue": 109539,
    "Full Edit Issue": 46145,
    "Log In": 9345,
    "Project Summary": 4279,
    "Search with JQL": 11818,
    "View Backlog": 5324,
    "View Board": 7540,
    "View Dashboard": 4570,
    "View Issue": 12038
  }
}
```

My Charts looked like so

![image](https://user-images.githubusercontent.com/12599965/61581200-77917980-ab1b-11e9-9b9c-ff5bd71c57b0.png)

![image](https://user-images.githubusercontent.com/12599965/61581206-8aa44980-ab1b-11e9-8023-c3d4f084a709.png)


I rendered both from this JSON above and an additional JSON that defines what Action means which PageURL/RestUrl. So if this is somehow retrievable from the sqlite result db, then this would be awesome :)

**Comment by ataraxie** [comment]
Nice! I guess it's the same basically. The data looks like this:
![image](https://user-images.githubusercontent.com/1646086/61581253-4feee100-ab1c-11e9-9e7b-df033acc8720.png)

I pull the bare numbers from the DB with a script and paste them into a spreadsheet that looks like this and generates the chart:
![image](https://user-images.githubusercontent.com/1646086/61581272-70b73680-ab1c-11e9-8d3e-89a54a69cd1c.png)

![image](https://user-images.githubusercontent.com/1646086/61581276-8593ca00-ab1c-11e9-9571-d56c005343d9.png)

**Comment by clouless** [comment]
Super Awesome :)

**Comment by ataraxie** [comment]
@clouless Did you mention once that you used an app for data generation in Jira?

**Comment by clouless** [comment]
Yes but it throws a lot of duplicate errors after some time and it takes forever and needs multiple restarts :-/ .

Therefore I used the prebuild data sets from Atlassian:

[**aws-infrastructure/.../DatasetCatalogue.kt**](https://github.com/atlassian/aws-infrastructure/blob/master/src/main/kotlin/com/atlassian/performance/tools/awsinfrastructure/api/DatasetCatalogue.kt)

 * 10GB https://s3.eu-central-1.amazonaws.com/jpt-custom-datasets-storage-a008820-datasetbucket-dah44h6l1l8p/dataset-631c70d4-084b-455c-9785-b01068b9f07c/database.tar.bz2
 * 8,6GB https://s3.eu-central-1.amazonaws.com/jpt-custom-datasets-storage-a008820-datasetbucket-dah44h6l1l8p/dataset-631c70d4-084b-455c-9785-b01068b9f07c/jirahome.tar.bz2

**Comment by ataraxie** [comment]
Wow thanks a lot! Such things don't exist for Confluence, right? Because this is exactly what I've been creating myself with Good Data Generator.

**Comment by ataraxie** [comment]
But are these MySQL? Haven't you used your amazing Docker scripts? I'm confused.

**Comment by clouless** [comment]
Yes and No :) I did not use the scripts but only the pre-built-containers to use with Kubernetes.
And since Atlassian provided MySQL 5.6 data-dir, I switched to MySQL for the performance tests.

For example my kubernetes yml for mysql

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jira-cluster-820-db
  namespace: atlassian
spec:
  selector:
    matchLabels:
      app: jira-cluster-820-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jira-cluster-820-db
    spec:
      nodeName: dbnode
      containers:
        - image: mysql:5.6
          name: jira-cluster-820-db
          ports:
            - containerPort: 3306
              name: mysql
          args: [ "--transaction-isolation=READ-COMMITTED", "--max-allowed-packet=512M", "--default-storage-engine=INNODB", "--character-set-server=utf8mb4", "--innodb-log-file-size=2G" ]
          volumeMounts:
            - name: jira-cluster-820-db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: jira-cluster-820-db-volume
          hostPath:
            path: /opt/k8s-host-path-volumes/jira-cluster-820-db/database
            type: Directory
---
# Note: We need the service so that a DNS record for the pod is generated!
apiVersion: v1
kind: Service
metadata:
  name: jira-cluster-820-db
  namespace: atlassian
spec:
  ports:
    - port: 3306
  selector:
    app: jira-cluster-820-db
  clusterIP: None
```

**Comment by ataraxie** [comment]
I didn't say thanks. Thanks! But actually, I have never used Kubernetes and I have no idea. Also, I really don't like the fact that this is now MySQL. I'm quite committed to your Docker setup by now, haha. I might try to populate a Postgres DB somehow and create my own archives.

I started to write a proper readme. I was wondering if you were interested at all in some kind of collaboration on E4. I'm quite sure that if some improvements were made it could gain some popularity in the Atlassian vendor community (I know that people have a really hard time doing the DC testing). Also, it's not bound to Atlassian. But I'm a bit afraid we don't have enough resources (and probably devops know how) to really keep working on it enough.

**Comment by clouless** [comment]
You could use [pgloader](https://tapoueh.org/blog/2017/07/from-mysql-to-postgresql/#migrate-from-mysql-to-postgresql) to migrate the provided mysql database to postgres.

You can start the mysql database like so directly with docker. Extract the database zip to e.g. `/dir/to/extracted-zip` and run:

```
docker run --rm \
           -p 3306:3306 \
            -v /dir/to/extracted-zip:/var/lib/mysql \
           -d mysql:5.6 \
             --transaction-isolation=READ-COMMITTED \
             --max-allowed-packet=512M \
             --default-storage-engine=INNODB \
             --character-set-server=utf8mb4 \
             --innodb-log-file-size=2G
```

Now you can connect to the DB with the credentials from the confluence-home zip dbconfig file.

Unfortunately I am also at my limit with resources for open source at the moment. I have a lot of stuff to finish with deadlines and cannot commit to any new tasks.
Also I really think that Atlassian should provide an easy way to test for performance. JPT is really good and I have adapted it for Confluence now and will stick with that, since I cannot invest time in another tool at the moment.
Maybe you can ask other big vendors to help you out. We are a really small vendor.
